# Generated by Django 2.1.1 on 2019-11-28 00:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_en', models.CharField(blank=True, default='', max_length=150)),
                ('poster_url', models.CharField(blank=True, default='', max_length=150)),
                ('open_date', models.CharField(blank=True, default='', max_length=50)),
                ('audience', models.IntegerField(blank=True, default=0)),
                ('show_time', models.IntegerField(blank=True, default=0)),
                ('user_rating', models.FloatField(blank=True, default=0)),
                ('nation', models.CharField(blank=True, default='', max_length=30)),
                ('watch_grade', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.TextField()),
                ('director', models.CharField(blank=True, default='', max_length=150)),
                ('actor', models.CharField(blank=True, default='', max_length=150)),
                ('genre', models.ManyToManyField(blank=True, related_name='movie_genres', to='movies.Genre')),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('review', models.CharField(max_length=150)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
